/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/uIAJHXMBxoC
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button";
import Link from "next/link";

export function Component() {
  return (
    <div className="flex min-h-[100dvh] flex-col items-center justify-center bg-background px-4 py-12 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-md text-center">
        <div className="space-y-3">
          <h1 className="text-3xl font-bold tracking-tighter text-foreground sm:text-4xl">
            Connect Your Crypto Wallet
          </h1>
          <p className="text-muted-foreground">
            To get started, please connect your crypto wallet to our platform.
          </p>
        </div>
        <div className="mt-6 space-y-4">
          <Button className="w-full">
            <WalletIcon className="mr-2 h-5 w-5" />
            Connect Wallet
          </Button>
          {/* <p className="text-sm text-muted-foreground">
            By connecting your wallet, you agree to our{" "}
            <Link href="#" className="underline" prefetch={false}>
              Terms of Service
            </Link>
            .
          </p> */}
        </div>
      </div>
    </div>
  );
}

function WalletIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 7V4a1 1 0 0 0-1-1H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4h-3a2 2 0 0 0 0 4h3a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1" />
      <path d="M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4" />
    </svg>
  );
}
